# Generated by Django 2.2 on 2019-04-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
