# Generated by Django 2.2 on 2019-04-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='auth',
            new_name='author',
        ),
    ]
